# Welcome to Jekyll!

### Site Settings ###
title               : Insights4YOU
description         : >-                                                  # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl             : ""                                                  # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
url                 : ""                                                  # the base hostname & protocol for your site, e.g. http://example.com
remote_theme        : insights4you-jekyll-theme                           # Change to your theme repository if you are using a fork
theme               : insights4you-jekyll-theme
keywords            : "your, keywords"
lang                : "en"

### Theme Settings ###
markdown            : kramdown
layout-dark         : false
themeColor          : "#206bc4"
useIconfont         : false

### GitHub Projects ###
github:
  user: marciopaiva

### Author Info ###
author:
  name              : Marcio Paiva Barbosa
  bio               : Solution Architect
  image             : https://avatars.githubusercontent.com/u/1004306?v=4 # or use your avatar eg. assets/image/
  email             : mpaivabarbosa@gmail.com
  linkedin          : marcio-paiva-barbosa
  github            : marciopaiva
  github-sponsor    : marciopaiva

### Site Plugins ###
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-github-metadata


### Navbar Settings ###
nav_exclude:               # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html

exclude:
  - logs
  - logs/build.log

# Build Settings
sass:
  style: compressed # For production
  load_paths:
    - _sass
