# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

### Site Settings ###
title               : Insights4YOU
description         : >-                                                  # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl             : ""                                                  # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
url                 : ""                                                  # the base hostname & protocol for your site, e.g. http://example.com
remote_theme        : insights4you-jekyll-theme                           # Change to your theme repository if you are using a fork
theme               : insights4you-jekyll-theme 
open_new_tab        : false                                               # Opens external URLs in new tab (works for posts, projects and navbar only)



### Site Plugins ###
plugins:
  - jekyll-feed