source "https://rubygems.org"

gem "insights4you-jekyll-theme", path: "../"

# Explicitly include Faraday gems
gem "faraday", "~> 2.7"
gem "faraday-retry", "~> 2.2"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-paginate", "~> 1.1"
  gem "jekyll-github-metadata", "~> 2.13"
end

# Windows and JRuby does not include zoneinfo files
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "webrick", "~> 1.7"
