name: gem publish

# This workflow automates the process of publishing the Ruby gem.
# It triggers only when a tag is created.

on:
  push:
    tags:
      - "v*" # Trigger only when a tag starting with "v" is created (e.g., v1.0.0)

jobs:
  publish:
    name: Publish Gem
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@b4ffde65f46336ab88eb53c9f6d47b10a34ccbe8 # Commit SHA for v4

    - name: Set up Ruby 3.1.4
      uses: ruby/setup-ruby@49d9cfa8aac1b9c1b8db6e418256a2d3185d4643 # Commit SHA for v1
      with:
        ruby-version: 3.1.4

    - name: Validate Gemspec
      run: |
        gem spec *.gemspec --validate

    - name: Cache Gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Build the Gem
      id: build_gem
      run: |
        bundle config set --local path 'vendor/bundle'
        gem build *.gemspec
        echo "GEM_FILE=$(ls *.gem)" >> $GITHUB_ENV

    - name: Test the Gem
      run: |
        gem install ${{ env.GEM_FILE }}
        rake test # Replace with your test command

    - name: Publish to GPR
      if: success()
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push --key github --host https://rubygems.pkg.github.com/${OWNER} ${{ env.GEM_FILE }}
      env:
        GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      if: success()
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        gem push ${{ env.GEM_FILE }}
      env:
        RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"

    - name: Clean Up Credentials
      if: always()
      run: |
        rm -rf $HOME/.gem/credentials

    - name: Upload Gem Artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-gem
        path: '*.gem'