name: gem publish

# This workflow automates the process of publishing the Ruby gem.
# It triggers only when a tag is created.

on:
  push:
    tags:
      - "v*" # Trigger only when a tag starting with "v" is created (e.g., v1.0.0)

jobs:
  publish:
    name: Publish Gem
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # Updated commit SHA for v4

    - name: Set up Ruby 3.1.1
      uses: ruby/setup-ruby@e5517072e87f198d9533967ae13d97c11b604005 # Commit SHA for v1.99.0
      with:
        ruby-version: 3.1.1

    - name: Build the Gem
      id: build_gem
      run: |
        gem build *.gemspec
        echo "GEM_FILE=$(ls *.gem)" >> $GITHUB_ENV

    - name: Publish to GPR
      if: success()
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push --key github --host https://rubygems.pkg.github.com/${OWNER} ${{ env.GEM_FILE }}
      env:
        GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      if: success()
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        gem push ${{ env.GEM_FILE }}
      env:
        RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"