name: gem build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Gem
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # Updated commit SHA for v4

    - name: Set up Ruby 3.1.4
      uses: ruby/setup-ruby@49d9cfa8aac1b9c1b8db6e418256a2d3185d4643 # Commit SHA for v1
      with:
        ruby-version: 3.1.4

    - name: Build the Gem
      run: |
        gem build *.gemspec