name: Ruby Gem

# This workflow automates the process of building and publishing the Ruby gem.
# It triggers on pushes to the "main" branch or pull requests targeting "main".
# The workflow builds the gem and publishes it to both GitHub Packages (GPR) and RubyGems.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.1.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.4

    - name: Publish to GPR
      run: |
        # Configure credentials for GitHub Packages (GPR)
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        # Build and push the gem to GitHub Packages
        gem build *.gemspec
        gem push --key github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      run: |
        # Configure credentials for RubyGems
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        # Build and push the gem to RubyGems
        gem build *.gemspec
        gem push *.gem
      env:
        RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
