name: Ruby Gem Build

# This workflow automates the process of building the Ruby gem.
# It triggers on pushes to the "main" branch or pull requests targeting "main".

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Gem
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.1.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.4

    - name: Build the Gem
      run: |
        gem build *.gemspec