name: gem build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Gem
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 3.1.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      - name: Generate Notifications Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Busca commits
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               "https://api.github.com/repos/marciopaiva/insights4you-jekyll-theme/commits?per_page=5" > commits.json

          # Converte JSON para YAML
          echo "_data/notifications.yml" >> .gitignore # Ignora o arquivo local
          jq -r '.[] | {
            title: .commit.message,
            description: "\(.commit.author.name) · \(.commit.author.date | sub("[.]000Z$"; "Z") | fromdateiso8601 | strftime("%b %-d, %Y")),
            link: .html_url,
            color: "blue"
          }' commits.json | yq -P > _data/notifications.yml
 
      - name: Commit and Push Notifications
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _data/notifications.yml
          git commit -m "Auto-update notifications.yml with latest commits" || echo "No changes to commit"
          git push

      - name: Build the Gem
        run: |
          gem build *.gemspec