name: gem build

# This workflow automates the process of building the Ruby gem.
# It triggers on pushes to the "main" branch or pull requests targeting "main".

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Gem
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@b4ffde65f46336ab88eb53c9f6d47b10a34ccbe8 # Commit SHA for v4

    - name: Set up Ruby 3.1.4
      uses: ruby/setup-ruby@49d9cfa8aac1b9c1b8db6e418256a2d3185d4643 # Commit SHA for v1
      with:
        ruby-version: 3.1.4

    - name: Build the Gem
      run: |
        gem build *.gemspec