name: gem build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Gem
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 3.1.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      # Instala jq e yq
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          pip install yq

      # Gera notifications.yml
      - name: Generate Notifications Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               "https://api.github.com/repos/marciopaiva/insights4you-jekyll-theme/commits?per_page=5" > commits.json

          jq -r '.[] | {
            title: .commit.message,
            description: "\(.commit.author.name) · \(.commit.author.date | sub("\\.000Z$"; "Z") | strptime("%Y-%m-%dT%H:%M:%SZ") | strftime("%b %e, %Y")),
            link: .html_url,
            color: "blue"
          }' commits.json > temp.json

          yq eval '.' temp.json > _data/notifications.yml
          rm temp.json

      # Commit automático
      - name: Commit and Push Notifications
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/marciopaiva/insights4you-jekyll-theme.git"
          git add _data/notifications.yml
          git commit -m "Auto-update notifications.yml" || echo "No changes to commit"
          git push origin main

      - name: Build the Gem
        run: |
          gem build *.gemspec