name: Gem CI/CD

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true

    # Add initial default value for GEM_FILE
    - name: Set default GEM_FILE
      run: echo "GEM_FILE=not-set" >> $GITHUB_ENV

    - name: Build Gem
      id: build_gem
      run: |
        gem build *.gemspec
        GEM_FILE=$(ls *.gem)
        echo "GEM_FILE=$GEM_FILE" >> $GITHUB_ENV
        echo "Built gem file: $GEM_FILE"

    # Add verification step
    - name: Verify Gem File
      run: |
        echo "Verifying gem file: ${{ env.GEM_FILE }}"
        test -f "${{ env.GEM_FILE }}" || exit 1

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gem-package
        path: ${{ env.GEM_FILE }}
        retention-days: 5

  publish:
    name: Publish Gem
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: gem-package

    # Add verification after download
    - name: Verify Downloaded Gem
      run: |
        GEM_FILE=$(ls *.gem)
        echo "GEM_FILE=$GEM_FILE" >> $GITHUB_ENV
        echo "Downloaded gem file: $GEM_FILE"
        test -f "$GEM_FILE" || exit 1

    - name: Publish to GitHub Packages
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push --key github --host https://rubygems.pkg.github.com/${OWNER} ${{ env.GEM_FILE }}
      env:
        GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        gem push ${{ env.GEM_FILE }}
      env:
        RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: "${{ env.GEM_FILE }}"
        generate_release_notes: true
        draft: false
        prerelease: false
